// Package protocol defines the HTTP API request and response types.
// These types are shared between the orchestrator (server) and agent (client).
package protocol

import "time"

// ============================================================
// Agent Registration
// ============================================================

// RegisterAgentRequest is sent by agents when they first connect.
type RegisterAgentRequest struct {
	// Unique agent identifier (UUID v4, generated by agent)
	AgentID string `json:"agent_id" validate:"required,uuid4"`

	// Lab host identifier (e.g., "ws1", "dc1") - from config or VM metadata
	LabHostID string `json:"lab_host_id" validate:"required,min=1,max=255"`

	// Machine hostname
	Hostname string `json:"hostname" validate:"required,min=1,max=255"`

	// Agent's IP address
	IPAddress string `json:"ip_address" validate:"required,ip"`

	// Labels for targeting (e.g., {"role": "workstation", "os": "windows"})
	Labels map[string]string `json:"labels" validate:"required"`

	// Agent software version
	Version string `json:"version" validate:"required"`
}

// ============================================================
// Agent Heartbeat
// ============================================================

// HeartbeatRequest is sent periodically by agents to indicate they're alive.
type HeartbeatRequest struct {
	// Current agent status
	Status string `json:"status" validate:"required,oneof=online busy error"`

	// IDs of jobs currently being executed
	CurrentJobs []string `json:"current_jobs,omitempty"`

	// Agent metrics for monitoring
	Metrics *AgentMetrics `json:"metrics,omitempty"`
}

// AgentMetrics contains performance metrics from the agent.
type AgentMetrics struct {
	// CPU usage percentage (0-100)
	CPUPercent float64 `json:"cpu_percent,omitempty"`

	// Memory usage percentage (0-100)
	MemoryPercent float64 `json:"memory_percent,omitempty"`

	// Total jobs completed since startup
	JobsCompleted int `json:"jobs_completed,omitempty"`

	// Total jobs failed since startup
	JobsFailed int `json:"jobs_failed,omitempty"`

	// Agent uptime in seconds
	UptimeSeconds int64 `json:"uptime_seconds,omitempty"`
}

// ============================================================
// Job Result Submission
// ============================================================

// JobResultRequest is sent by agents after completing a job.
type JobResultRequest struct {
	// Final job status
	Status string `json:"status" validate:"required,oneof=completed failed"`

	// When the agent started executing the job
	StartedAt time.Time `json:"started_at" validate:"required"`

	// When the agent finished executing the job
	CompletedAt time.Time `json:"completed_at" validate:"required"`

	// Execution result (structure depends on action type)
	Result *JobResult `json:"result,omitempty"`

	// Error details if status is "failed"
	Error *JobError `json:"error,omitempty"`
}

// JobResult contains the outcome of a successful job execution.
type JobResult struct {
	// Action-specific result fields
	// For browsing: urls_visited, pages_loaded, links_clicked
	// For file_activity: files_created, files_modified, files_read
	// For email: emails_sent, emails_received
	// For process: processes_spawned, total_runtime_ms
	Data map[string]interface{} `json:"data,omitempty"`

	// Summary message
	Summary string `json:"summary,omitempty"`

	// Duration of execution in milliseconds
	DurationMs int64 `json:"duration_ms,omitempty"`
}

// JobError contains details about a failed job.
type JobError struct {
	// Error code for categorization
	Code string `json:"code" validate:"required"`

	// Human-readable error message
	Message string `json:"message" validate:"required"`

	// Whether this error is retryable
	Retryable bool `json:"retryable"`

	// Stack trace or additional details (optional)
	Details string `json:"details,omitempty"`
}

// ============================================================
// Scenario Submission (API endpoint)
// ============================================================

// CreateScenarioRequest is used to submit a new scenario via API.
type CreateScenarioRequest struct {
	// Human-readable name for the scenario
	Name string `json:"name" validate:"required,min=1,max=255"`

	// Optional description
	Description string `json:"description,omitempty" validate:"omitempty,max=2000"`

	// The lab intent to generate a scenario from
	Intent *IntentInput `json:"intent,omitempty"`

	// Or a pre-validated DSL scenario (skips AI planning)
	Scenario *ScenarioInput `json:"scenario,omitempty"`
}

// IntentInput is the user-provided intent for AI planning.
type IntentInput struct {
	// Lab type identifier
	LabType string `json:"lab_type" validate:"required"`

	// Lab duration in minutes
	DurationMinutes int `json:"duration_minutes" validate:"required,min=5,max=480"`

	// Difficulty level
	Difficulty string `json:"difficulty" validate:"required,oneof=easy medium hard"`

	// Scenario goals/objectives
	Goals []string `json:"goals,omitempty"`

	// Additional context for the AI planner
	Context string `json:"context,omitempty" validate:"omitempty,max=5000"`

	// Noise intensity
	NoiseIntensity string `json:"noise_intensity,omitempty" validate:"omitempty,oneof=low medium high"`
}

// ScenarioInput is a pre-validated scenario for direct submission.
type ScenarioInput struct {
	// The complete scenario definition (JSON)
	Definition string `json:"definition" validate:"required"`
}

// ============================================================
// Impersonation User Management
// ============================================================

// CreateImpersonationUserRequest is used to create a new impersonation user.
type CreateImpersonationUserRequest struct {
	// Full username (DOMAIN\user)
	Username string `json:"username" validate:"required"`

	// Domain name
	Domain string `json:"domain" validate:"required"`

	// SAM account name
	SAMAccountName string `json:"sam_account_name" validate:"required"`

	// Display name (optional)
	DisplayName string `json:"display_name,omitempty"`

	// Department (optional, used for AI persona matching)
	Department string `json:"department,omitempty"`

	// Job title (optional)
	Title string `json:"title,omitempty"`

	// Lab host IDs where this user can be impersonated (optional)
	AllowedHosts []string `json:"allowed_hosts,omitempty"`

	// Behavior hints for AI planner (optional)
	Persona *UserPersonaInput `json:"persona,omitempty"`
}

// UpdateImpersonationUserRequest is used to update an impersonation user.
type UpdateImpersonationUserRequest struct {
	DisplayName  *string          `json:"display_name,omitempty"`
	Department   *string          `json:"department,omitempty"`
	Title        *string          `json:"title,omitempty"`
	AllowedHosts []string         `json:"allowed_hosts,omitempty"`
	Persona      *UserPersonaInput `json:"persona,omitempty"`
}

// UserPersonaInput contains behavior hints for the AI planner.
type UserPersonaInput struct {
	// Typical applications this user runs
	TypicalApps []string `json:"typical_apps,omitempty"`

	// Typical websites this user visits
	TypicalSites []string `json:"typical_sites,omitempty"`

	// Typical file types this user works with
	FileTypes []string `json:"file_types,omitempty"`

	// Work hours (optional)
	WorkHours *WorkHoursInput `json:"work_hours,omitempty"`
}

// WorkHoursInput defines when a user typically works.
type WorkHoursInput struct {
	Start int `json:"start" validate:"min=0,max=23"` // Hour (0-23)
	End   int `json:"end" validate:"min=0,max=23"`   // Hour (0-23)
}

// BulkCreateImpersonationUsersRequest is used to create multiple users at once.
type BulkCreateImpersonationUsersRequest struct {
	Users []CreateImpersonationUserRequest `json:"users" validate:"required,min=1"`
}
